### ISSUE TITLE
Modules loaded via Hapi Glue manifest are identified as not used

### ISSUE THREAD

**Issue by dpmott** [depcheck/depcheck#209]
See Hapi Glue API documentation & usage here:
https://github.com/hapijs/glue/blob/master/API.md#usage

Given a module which defines a manifest object containing registrations containing any of:
* registrations[x].plugin.options.reporters.reporter[x].module: [module name]
* registrations[x].plugin.register: [module name]
* registrations[x].plugin: [module name]

then Hapi Glue will dynamically require() the specified dependencies, but depcheck will have no knowledge of this.

See attached [manifest.zip](https://github.com/depcheck/depcheck/files/959465/manifest.zip), containing an example manifest.js.

**Comment by travi** [comment]
i would love this ability as well. one of my manifests that could be used as an example: https://github.com/travi/travi.org-admin/blob/master/src/server/manifest.js

**Comment by dpmott** [comment]
If anyone has a suggestion of how best to fix this, I could start working on putting together a pull request as early as next week.

**Comment by travi** [comment]
ive been using actual `require` in my manifests lately so that i can use webpack to bundle the server, so i dont this issue applies anymore with that approach

**Comment by rumpl** [comment]
@dpmott this would need a new detector, similar to the one we use to detect [calls to require](https://github.com/depcheck/depcheck/blob/master/src/detector/requireCallExpression.js).

This detector would be more complicated since you will have to find the value of the manifest, the require detector only detects calls to require like `require('react')` and not things like 

```javascript
const dep = 'react';
require(dep);
```
