### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by tomekwi** [depcheck/depcheck#21]
Hi, and first of all thanks for a great piece of code.

Have you considered adding support for ES6 files – run via [babel](https://www.npmjs.com/package/babel) or [traceur](https://www.npmjs.com/package/traceur)?

It should be as simple as looking for `import .+ from "<dependency>(/.+)?";` as well as  `require\("<dependency>(/.+)?"\);`.

**Comment by juancabrera** [comment]
Running through the same issue. It's saying that some packages are not being used and actually they are. I'm also assuming this is because of the ES6 syntax.

As an example it's saying the package ```fluxible-plugin-routr``` is not in use, but actually its on a root file app.js, this is the syntax I'm using to load it.
```javascript
import routrPlugin from 'fluxible-plugin-routr';
```

**Comment by rumpl** [comment]
Hey guys,

I will look into it, ES6 support is definitely a must have.

Thanks for taking the time to write an issue.

**Comment by callum** [comment]
I wonder if a more versatile approach would be to allow piping via stdin, then it would be possible to do something like `babel file.js | depcheck`.

**Comment by dantman** [comment]
I have this issue too. I started using React in my code recently. I run `.es6` and `.jsx` files with babel so I can use JSX and ES6 functionality in some of my code.

My requires are still traditional `require(...)` calls. But because depcheck only looks for files ending in `.js` and parses ES3/ES5. Any module I only use in ES6/JSX code like `require('classnames')` is marked as not used.

I'm not using depcheck directly. Instead I'm using `npm-check` and this has an effect on that.

**Comment by bettiolo** [comment]
:+1: for es6 support in .js and .jsx

**Comment by lijunle** [comment]
:+1: here. :)

**Comment by lijunle** [comment]
I think that the package [detective-es6](https://www.npmjs.com/package/detective-es6) can be leveraged to resolve this issue.

**Comment by geirsagberg** [comment]
+1 :)

**Comment by christophehurpeau** [comment]
:+1:

**Comment by lijunle** [comment]
@rumpl I have implemented the support for ES6 in #29, could you please take a look?

**Comment by ngryman** [comment]
:+1:

**Comment by woodb** [comment]
This has been closed in #29

**Comment by lijunle** [comment]
Hi, all.

Because @rumpl don't response on my PR. I decide to publish my fork to NPM and rename to `depcheck-es6`. It is a drop-in replacement for `depcheck` package.

Modify your `package.json` to replace `depcheck` to `depcheck-es6` and update your `require` or `import` statements.

Personally, besides ES6 support, I am proposing supports for JSX and gulp. If anybody have some ideas, please open an issue in [my fork](https://github.com/lijunle/depcheck-es6).

**Comment by lijunle** [comment]
Hi all, I am back. :smiley:

Depcheck-es6 is merged back to original depcheck now. I have released [version 0.5.9](https://www.npmjs.com/package/depcheck) on depcheck package in NPM.

Thanks for @rumpl moving the repo under the org. I will continue to develop and maintain the project.
