### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by vmeurisse** [depcheck/depcheck#213]
There are a few fixes that are not yet released in any version https://github.com/depcheck/depcheck/compare/0.6.7...master. 
In particular https://github.com/depcheck/depcheck/pull/196 would be very useful.

Could you please release a new version to npm?

**Comment by rumpl** [comment]
Hey @vmeurisse,

Sure, I'll get to it first thing tomorrow morning, sorry for the inconvenience.

**Comment by lijunle** [comment]
Hey, Djordje.

You could just add a new tag with version name and the release note, then
push it to Github. The CI build will publish it to NPM.

2017年6月28日 上午5:29，"Djordje Lukic" <notifications@github.com>写道：

Hey @vmeurisse <https://github.com/vmeurisse>,

Sure, I'll get to it first thing tomorrow morning, sorry for the
inconvenience.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/depcheck/depcheck/issues/213#issuecomment-311491511>,
or mute the thread

**Comment by niftylettuce** [comment]
?

**Comment by jwhitmarsh** [comment]
@lijunle Any chance this can get published?

**Comment by lijunle** [comment]
Sorry, James.

There are some ESLint failures and test failures. Could you please help to
fix them? Then, I can publish a new version.

Thanks!
Junle

**Comment by jwhitmarsh** [comment]
I've just forked the repo and all the tests are completing. 

The lint errors are all `no-return-assign` errors, so this:
```js
      data => (log = data),
      data => (error = data),
```

becomes this:
```js
      (data) => {
        log = data;
        return log;
      },
      (data) => {
        error = data;
        return error;
      },
``` 

I prefer the first one, but it's not my repo and I don't want to step on toes and change code format, but I'd recommend we just disable the `no-return-assignment` rule in eslint.

**Comment by lijunle** [comment]
We don't need to return the value.

This is fine:

>  (data) => { log = data; },

2017年10月10日 16:48，"James" <notifications@github.com>写道：

**Comment by lijunle** [comment]
Hi, thank you to @jwhitmarsh . The version 0.6.8 is out. I am closing this issue.
