### ISSUE TITLE
Support for Typescript webpack files

### ISSUE THREAD

**Issue by cbrianball** [depcheck/depcheck#246]
It looks like the webpack special only works if the webpack config file is a .js file. I use .ts files for my webpack configuration.

**Comment by lijunle** [comment]
Hi,

You are right. It is only recognize the .js file. It could be great that
you can help on it.

Brian Ball <notifications@github.com>于2018年2月27日 周二上午5:21写道：

**Comment by sveyret** [comment]
FI, I'm currently working on this…

**Comment by rumpl** [comment]
Closed with #449

**Comment by sveyret** [comment]
Should we re-open this one because of the `ts-node` requisite? Or simply add a comment in any document?

**Comment by rumpl** [comment]
Yeah, I'll reopen it, so that I don't search why:

The regex for webpack configuration was changed to accept .ts files but we can only require this kind of file if depcheck is used as a library with a ts-node runtime.

For this to trully work we need a way to be able to load .ts configuration files. This will surely mean that we need to depend on typescript directly, which I don't mind that much.

**Comment by sveyret** [comment]
@rumpl did you receive my e-mail? I sent it to you GMail account from a personal server, and I know that GMail is sometimes touchy about personal servers, and so may put e-mails in spams.

**Comment by rumpl** [comment]
Just saw it, the email I have on github is an email that I don't look every day, will respond today, have to clean up my appartment now :)

**Comment by sveyret** [comment]
PR #459 now should fully correct the issue. @rumpl, I think it can be closed.
