### ISSUE TITLE
Modules with same name as a built-in (e.g. 'path') are incorrectly identified as unused dependency

### ISSUE THREAD

**Issue by donaldm314** [depcheck/depcheck#251]
It appears as though path is incorrectly identified as an unused dependency.

```
dmurray@ss9:...andbox/depcheck-path 0> npm run depcheckjson

> depcheck-path@1.0.0 depcheckjson /home/dmurray/sandbox/depcheck-path
> depcheck --json|json

{
  "dependencies": [
    "path"
  ],
  "devDependencies": [],
  "missing": {},
  "using": {
    "depcheck": [
      "/home/dmurray/sandbox/depcheck-path/package.json"
    ]
  },
  "invalidFiles": {},
  "invalidDirs": {}
}
dmurray@ss9:...andbox/depcheck-path 0> 
```

This is a trivial demo project, containing server.js which includes log.js, which uses path.

To reproduce:
1. unpack depcheck-path.zip
2. npm install
3. npm run depcheckjson

[depcheck-path.zip](https://github.com/depcheck/depcheck/files/1874044/depcheck-path.zip)

**Comment by abelosorio** [comment]
Facing this same issue.

**Comment by Berkmann18** [comment]
Any updates regarding this issue?

**Comment by rumpl** [comment]
Hi all,

I'm having a hard time understanding why would you install a dependency that is either [useless](https://github.com/DiegoRBaquero/node-os/blob/master/index.js) or is an exact copy of the nodejs core module... In both cases the dependency is indeed useless since it comes with node.

Could you @Berkmann18 or @donaldm314 explain the use case please?

**Comment by Berkmann18** [comment]
@rumpl In my case, I'm here because of [this issue](https://github.com/dylang/npm-check/issues/299) where the dependency (`lodash`) was classified as unused... Which wasn't.

Regarding using native modules (read dependencies that are _already_ imported), I guess it would make sense to flag said dependencies as unneeded (note: the "un**needed**" as opposed to the "un**used**").

**Comment by Berkmann18** [comment]
@rumpl Did that answer your question?

**Comment by rumpl** [comment]
@Berkmann18 the other issue is an issue about monorepos, for this one, I gues that we can say it's unneeded but this would be very low on my list of things to do.

**Comment by Berkmann18** [comment]
Fair enough.
