### ISSUE TITLE
Symlinked files are ignored

### ISSUE THREAD

**Issue by magillj** [depcheck/depcheck#256]
depcheck does not process source files that are symlinked to a file outside the package being analyzed.

This is simple to repro:

1. Create a new package with a blank package.json
2. Add a js file where the only line is `var test = require('lodash');`
3. Running depcheck on that package properly shows that the dependency lodash is missing
4. Move the js file somewhere outside the package and symlink to it inside the package
5. depcheck reports no issues

I found [the problematic code](https://github.com/depcheck/depcheck/blob/master/src/check.js#L164): only regular files (the type 'file') are checked. This group does not include the 'link' category, which contains the symlinks in question. That's why they're ignored.

Context: the reason I have to worry about symlinks is that I'm using this within a [bazel build system](https://github.com/bazelbuild/bazel), which symlinks groups of source files to sandbox environments where tests run.

**Comment by mnkhouri** [comment]
Hi @magillj, thank you for the detailed issue report! The module we're using to enumerate files, walkdir, [supports an option to follow symlinks](https://www.npmjs.com/package/walkdir#arguments). This option has been off in this project [since the very first commit](https://github.com/depcheck/depcheck/commit/1b753270fb01c3fb0b90431ca051b23dd5379f8a#diff-168726dbe96b3ce427e7fedce31bb0bcR142)!

I don't see a reason why we couldn't turn this option on 🤔  

A PR with this change as well as a test to cover it would be very welcome :) might you have time to take a shot at a PR? If not, no worries, I'll try to get to it soon

**Comment by magillj** [comment]
Sure I might be able to give it a shot within the next couple weeks

**Comment by mzyil** [comment]
any updates on this?

**Comment by rumpl** [comment]
@mzyil Not really no. Is your use case the same as @magillj ?

If not, could you tell me what is your use case?

**Comment by rumpl** [comment]
So yeah, I have an update on this. OF COURSE SYMLINKS ARE A PITA ON WINDOWS!

😢

Will try to find a solution.

**Comment by rumpl** [comment]
Done, will be available in the next release of depcheck. 

Sorry it took so long, real life got in the way :)

Cheers

**Comment by mzyil** [comment]
Thanks for the update! There is one more feature that we would like, will open another issue about that soon.

However may I suggest you make the following symlinks feature optional? Not our use case per se, but you may want to honor `NODE_PRESERVE_SYMLINKS` env var for example, in very rare cases one may have generated files in the repository that they don't care.

**Comment by rumpl** [comment]
Oh, I didn't know about `NODE_PRESERVE_SYMLINKS`, you learn every day :)

Would you like to make a PR for this? This would be a great time to drop node 6 support too (`NODE_PRESERVE_SYMLINKS` was added in v7.1.0.

**Comment by mzyil** [comment]
I'm planning to open a PR anyway, I will see what I can do
