### ISSUE TITLE
Monorepo support?

### ISSUE THREAD

**Issue by KaboomFox** [depcheck/depcheck#349]
### Feature request description
I am wondering if we want to support monorepos out of the box. We could look for all package.json files.
### Code snippets (if applicable)

```javascript
#!/usr/bin/env node

const depcheck = require('depcheck');
const glob = require('globby');
const fs = require('fs');
const path = require('path');

const IGNORE_PACKAGES = [
];

const rootDir = path.resolve(__dirname, '../');

const getPackages = async () => {
  const packages = await glob('**/package.json', { ignore: ['**/node_modules/**'] });
  if (packages.length === 0) {
    throw new Error('Did not find \'packages\'');
  }
  const PackageContent = [];
  packages.forEach(packagePath =>  {
    try {
      const packageJsonString = fs.readFileSync(packagePath, 'utf8');
      const packageJson = JSON.parse(packageJsonString);

      const pathToPackageJson = `${rootDir}/${packagePath}`;

      const pkg = {
        location: path.dirname(pathToPackageJson),
        name: packageJson.name,
      };
      PackageContent.push(pkg);
    } catch (err) {
      console.log(`Couldn't find a 'package.json' for ${packagePath}. Skipping. ${err}`);
    }
  });
  return PackageContent;
};

(async () => {
  console.log('*** NOTE: Double check usage before removing a package***');
  const packages = await getPackages().catch(err => {
    console.log(`Error in getPackages ${err}`);
  });

  const unusedPackages = [];

  for (const pkg of packages) {

    console.log(`\nChecking ${pkg.name} for unused deps.`);

    const opts = {
    };


    const results = await depcheck(pkg.location, opts);
    const individualPackageDeps = results.dependencies.filter(dep => !IGNORE_PACKAGES.includes(dep));

    if (individualPackageDeps.length !== 0) {
      console.log(individualPackageDeps.join('\r\n'));
      unusedPackages.push(...individualPackageDeps);
    }

  }
  if (unusedPackages.length !== 0 ) {
    console.log(`\nYou have unused packages: \n${unusedPackages.join('\r\n')}\n` );
    process.exit(1);
  }

})().catch(err => { console.log(err);});
```

### Any extra info
 We could either just include this example in the docs or make it the default functionality. What do you think?

**Comment by rumpl** [comment]
There is already [a discussion about yarn workspaces](https://github.com/depcheck/depcheck/issues/245).

I think that down the line depcheck should support yarn workspaces, but then it should also support lerna.

A couple of things about your code:
- we should get the list of packages from the root lerna.json or the root package.json
- we should think a little about the output when in a workspace, so that it's clear to the user where the error is

There is however one thing that bothers me about workspaces, in the #245 @benjie talks about two modes:

> Mode 1 (independent workspaces, e.g. to be published to npm): each individual workspace is expected to have its own deps specified in the workspace's own package.json (and the root package.json is basically ignored dependencies-wise)
>
> Mode 2 (dependent workspaces, e.g. to be ran in the context of the monorepo): each individual workspaces is expected to have its own deps specified in the workspace's own package.json OR the root package.json

I really dislike the second mode where they put dependencies in the root package.json. If we want to support workspaces we need to be clear about what means that a package declares a dependency and if we should support hacks like the second mode.

Would you like to do this one @KaboomFox ?

**Comment by benjie** [comment]
I suggest you only support mode 1. Typically mode 2 is only used for repo-wide tooling such as `lerna` itself, `eslint`, etc. Mode 2 is actually super dangerous to support if you're planning to publish to npm because it can hide the fact that dependencies are missing.

I don't think we need support for lerna; I use it with graphile-engine but I don't think depcheck would even need to know it exists to validate the repo with yarn workspaces.

**Comment by rumpl** [comment]
Agreed. 

But whst about lerna without yarn workspaces?

**Comment by benjie** [comment]
That's a separate feature, IMO, though it will likely have significant overlap.

**Comment by KaboomFox** [comment]
sounds like this isn't something we want to support. No problem.

**Comment by rumpl** [comment]
Wait what, no! I mean yeah, we can close this one since it's a duplicate of #245 but we should support yarn workspaces, I'm OK if we support only the mode 1 that @benjie suggested.

**Comment by rumpl** [comment]
I'm sorry if I wasn't clear enough, I was more thinking out loud.
