### ISSUE TITLE
Error when running from script

### ISSUE THREAD

**Issue by MarcPro37** [depcheck/depcheck#531]
script: 
"depcheck": "depcheck --ignore-dirs=dist,results"
When I run npm run depcheck I got this:
![image](https://user-images.githubusercontent.com/55714202/77769272-5e35bb00-7022-11ea-812f-5d5db33a562e.png)

It works but finish with an error.

**Comment by rumpl** [comment]
Hey @MarcPro37 

Yes, depcheck will have a non-zero return value if it finds errors (by errors I mean missing dependencies or unused dependencies), you will need to add a `|| true` to your script if you want to ignore the error. Depcheck returns a non-zero exit code so that it can be added to your CI and make it fail if you have problems in your dependencies.

I will close this issue, feel free to open a new one if you think there is a problem with depcheck
