### ISSUE TITLE
Option to exit without error code (when running via "npm run depcheck")

### ISSUE THREAD

**Issue by seanlindsay101** [depcheck/depcheck#533]
depcheck exits with an error code (-1) when it finds unused dependencies. If run as part of an npm script, this causes the script to terminate with npm's verbose error report.

Ideally, I'd like an option to exit successfully, even if it finds unused dependencies. This way it can be part of a sequence of code-checking scripts.

I would like to take a crack at this, but I wanted some feedback first about how others use depcheck, and whether anyone relies on the error code.

**Comment by rumpl** [comment]
Hey @seanlindsay101 

Depcheck exits with an error code so that it can be used in CI systems. I have seen people do "depcheck || true" to discard the exit code. One other way would be to write a simple script in [js to call depcheck](https://github.com/depcheck/depcheck#api) that will always return 0.

I'm not aware of other command line tools that have, say, a flag to tell it to always return 0. How would you implement this?

**Comment by seanlindsay101** [comment]
You're right, thanks. Newbie question.

**Comment by jeremy-daley-kr** [comment]
@rumpl I'm using `child_process.exec()` to `npx depcheck`, and that helped. It kept exiting otherwise. It'd be nice if there was a `--prevent-exit` flag or something... but this works for now:

```js
  exec('npx depcheck ./some/path --json || true')
```

Thanks!
