### ISSUE TITLE
False positive: webpack externals

### ISSUE THREAD

**Issue by clar-cmp** [depcheck/depcheck#566]
In our case, we're directly importing `synchronized-promise` which has a dependency on `deasync`. However, we also list `deasync` in our `package.json` because we want to pin a version for it in our webpack externals.

Because `deasync` is a native Node module, it can't be directly included in webpack and must be included externally. So, in our `webpack.config.js`, we explicitly list `deasync` in our webpack externals.

Even when including `webpack` in specials, this is listed as an unused dependency.

So, the specific request:

1. Potentially through a `webpack-externals` special
2. If a package is required by a used dependency (i.e. a transitive/indirect dependency)
3. If that package is exported in `externals` in the webpack config
4. It should be marked as used

**Comment by rumpl** [comment]
If I understand correctly, the issue here is not weback, or deasync or externals. The real problem is that you are installing `deasync` that you do not use directly in your code. In this case it's best to add `deasync` to the list of `ignores` when you run depcheck. How do you make sure that the version of `deasync` you have is compatible with `synchronized-promise`?

**Comment by clar-cmp** [comment]
That's a fair point, honestly; when I have a bit more time later I'll try to look into this a bit more and get back to you.

**Comment by clar-cmp** [comment]
I'm fine with filing this as a bug to serverless-webpack, since the main issue is that it tries to install externals via yarn and complains about the lock file being out of date. Closing.
