### ISSUE TITLE
Fails to parse TypeScript files with <> angle bracket casting

### ISSUE THREAD

**Issue by a7medkamel** [depcheck/depcheck#585]
If a typescript file contains an `<>` cast, depcheck fails to parse the file

```SyntaxError: Unexpected token, expected \"}\"```

ex:
```
<SomeType> {
    a: 'text_a',
    b: 'text_b'
}
```

**Comment by rumpl** [comment]
@a7medkamel thaks for reporting this, unfortunately I am unable to reproduce, could you create a sample repository with this error please?

**Comment by apancutt** [comment]
Affecting all my TS projects - [demo repo](https://github.com/apancutt/depcheck-585)

**Comment by rumpl** [comment]
Ah yes, there was another issue opened and this is because we activate JSX on our TS parser and you can't use `<>` for type casting, you need to use the [as operator](https://www.typescriptlang.org/docs/handbook/jsx.html#the-as-operator)

**Comment by apancutt** [comment]
We can't rewrite our apps just to get depcheck to work. We depend on this tool for our JS apps and works great, so would be a shame not to be able to use it across our TS apps too.

Is this behaviour by design or would a PR be welcomed?

In the meantime, is there any workaround? I've tried `depcheck --parsers '**/*.ts:typescript'` which I thought would disable all other parsers no joy.

**Comment by apancutt** [comment]
What about conditionally adding the `jsx` plugin if the `filename.endsWith('.tsx')`?

**Comment by rumpl** [comment]
A PR would be more than welcome, the problem is [this line](https://github.com/depcheck/depcheck/blob/main/src/parser/typescript.js#L13). We *could* create two separate parsers, one for typescript and one for tsx. Or, and this would be more work, have a way to activate/deactivate parser plugins.

One workaround I can think of is to write your own parser and pass it to depcheck, writing it would be easy, you copy the typescript.js file I linked above and remove the `jsx` plugin and then call depcheck programatically (example can be found [here](https://github.com/depcheck/depcheck#api)).

**Comment by rumpl** [comment]
> What about conditionally adding the `jsx` plugin if the `filename.endsWith('.tsx')`?

This would break too much react projects unfortunately, most of the projects I saw use the `.ts` extension for their components

**Comment by rumpl** [comment]
> We could create two separate parsers, one for typescript and one for tsx.

This actually wouldn't work because it would still break for a lot of people.

Your best bet would be to create your own parser then until we find a nice way to configure parser plugins.

Sorry there aren't better solutions

**Comment by rumpl** [comment]
Thinking about this some more, the `--parsers` flag can only use the already defined parsers in depcheck, if [we change how we get the parsers](https://github.com/depcheck/depcheck/blob/main/src/cli.js#L15) and make it `require` a file inside your project that defines a parser then you could do something like `depcheck --parsers '**/*.ts:file://./path/to/my/typescript-parser.js'`

Hope this makes sense. If it does I would be more that happy to review/merge/publish a new version of depcheck with this feature.

**Comment by apancutt** [comment]
Or perhaps a `--disable-plugins` CLI option?

**Comment by rumpl** [comment]
> Or perhaps a `--disable-plugins "jsx,plugin2,..."` CLI option?

Not sure I like it because you can't really easily say what plugin you want to disable for what parser. Also you can't activate/deactivate plugins for different types of files or different directories

**Comment by apancutt** [comment]
Another option is `--disable-plugins "<plugin>[:<parser>][:<glob>],<plugin2>..."` (where `<parser>` and `<glob>` are optional) but this is on the edge of user-unfriendly territory.

I don't like the idea of creating a custom parser since that also creates user unfriendliness. When you have multiple projects all wanting the same custom parser you'll end up needing to roll your own `depcheck` package.

>> We could create two separate parsers, one for typescript and one for tsx.

> This actually wouldn't work because it would still break for a lot of people.

Could you explain why? I'm thinking a `typescript-nojsx` parser would be more portable since it could be opted into via a package script (e.g. `{"depcheck": "depcheck --parsers **/*.ts:typescript-nojsx" }`). This would work assuming that default parsers are disabled if the `--parsers` option is provided(?)
