### ISSUE TITLE
Hard time to get it to work with a project that has .mjs files

### ISSUE THREAD

**Issue by Milad** [depcheck/depcheck#615]
### Bug Description

I have a project that has mjs files. Depcheck doesn't check them out of the box.

### Code snippets

Where the dependency is used:

index.mjs:
```javascript
import axios from 'axios';
```

Where the dependency is listed in package.json:

```
{
  "name": "my-depcheck",
  "version": "1.0.0",
  "description": "",
  "main": "index.mjs",
  "scripts": {
    "depcheck": "depcheck",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "depcheck": "^1.3.1"
  },
  "dependencies": {
    "axios": "^0.21.0"
  }
}
```

### Versions

- `node -v`: `v14.15.1`
- `npm -v`: `6.14.9`
- `depcheck --version`: `1.3.1`

### Extra info

I tried to create a file `.depcheckrc` but it didn't help!

```yaml
parsers:
  '*.mjs':
    - 'es6'
```

JSON output:
```
{
  "dependencies": [
    "axios"
  ],
  "devDependencies": [],
  "missing": {},
  "using": {
    "depcheck": [
      "~/Projects/my-depcheck/package.json"
    ]
  },
  "invalidFiles": {},
  "invalidDirs": {}
}
```

**Comment by rumpl** [comment]
Hey @Milad 

Could you try with this configuration please:

```yaml
parsers:
  '**/*.mjs':
    - 'es6'
```

**Comment by Milad** [comment]
Thanks @rumpl! It worked!

I'd guess that it makes sense to update the documentation [here](https://github.com/depcheck/depcheck/blob/main/doc/pluggable-design.md#use-parser-from-a-configuration-file)

**Comment by Milad** [comment]
Created #616

**Comment by itsMapleLeaf** [comment]
The docs update is appreciated, but I figure this should work by default, and probably for `.cjs` as well

**Comment by rumpl** [comment]
> The docs update is appreciated, but I figure this should work by default, and probably for `.cjs` as well

I honestly have no idea what an mjs or a cjs is

**Comment by itsMapleLeaf** [comment]
`mjs` files are always loaded as ESM, and `cjs` files are always loaded as commonjs. They're helpful to reduce ambiguity

Refs:

- https://nodejs.org/docs/latest/api/esm.html#esm_introduction
- https://v8.dev/features/modules#mjs

**Comment by thorsent** [comment]
The `parsers` config seems to override the defaults, so if you're using different types of files then you'll need to provide all of them, including what would otherwise be built in. Here's a complete list that includes the node and typescript ES6/CommonJS extensions. If you're using Coffeescript, Svelte, Vue etc then you can follow this syntax and add those extensions. Here are all the builtins (https://github.com/depcheck/depcheck/tree/main/src/parser)

```
parsers:
  "**/*.mjs":
    - 'es6'
  "**/*.cjs":
    - 'es6'
  "**/*.mts":
    - 'typescript'
  "**/*.cts":
    - 'typescript'
  "**/*.jsx":
    - 'jsx'
  "**/*.tsx":
    - 'typescript'
  "**/*.ts":
    - 'typescript'
  "**/*.js":
    - 'es6'
```

For the maintainers, cjs,mjs,cts,mts are becoming very common and it would be worth adding them as standard types. This is an excellent primer: https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
